In [2]:
import numpy as np
import cv2
import socketio
import base64

In [3]:
imdata = 0

sio = socketio.Client()

In [8]:
"""
@는 데코레이터임
https://bluese05.tistory.com/30 설명
"""

@sio.event
def streaming(data):
    data = cv2.imdecode(np.frombuffer(base64.b64decode(data), dtype='uint8'), cv2.IMREAD_COLOR)
    print(data)
    global imdata
    imdata = data

In [10]:
sio.connect('http://localhost:746')

while True:
    sio.on('streaming', streaming)
    cv2.imshow('Person Detect', imdata)
    if cv2.waitKey(1) == 13:
        break
cv2.destroyAllWindows()
sio.disconnect()

[[[108 112 117]
  [110 114 119]
  [112 117 120]
  ...
  [236 232 214]
  [235 230 215]
  [235 230 215]]

 [[108 112 117]
  [110 114 119]
  [112 117 120]
  ...
  [237 233 215]
  [236 231 216]
  [236 231 216]]

 [[110 113 118]
  [111 114 119]
  [113 116 120]
  ...
  [239 233 214]
  [240 233 216]
  [240 233 216]]

 ...

 [[ 72  50  55]
  [ 54  32  37]
  [ 47  27  32]
  ...
  [173 166 147]
  [172 166 147]
  [169 163 144]]

 [[ 58  36  48]
  [ 52  32  44]
  [ 51  34  45]
  ...
  [171 164 144]
  [172 165 145]
  [173 166 146]]

 [[ 54  34  47]
  [ 47  29  42]
  [ 44  25  40]
  ...
  [168 161 141]
  [170 163 143]
  [174 167 147]]]
[[[109 114 115]
  [109 114 115]
  [110 115 116]
  ...
  [231 233 214]
  [231 233 214]
  [229 233 214]]

 [[107 112 113]
  [109 114 115]
  [111 116 117]
  ...
  [232 233 213]
  [232 234 215]
  [229 234 213]]

 [[110 114 115]
  [112 116 117]
  [114 118 119]
  ...
  [232 234 212]
  [233 234 214]
  [232 235 213]]

 ...

 [[ 61  49  45]
  [ 45  34  30]
  [ 39  27  23]
  ..

[[[100 115 118]
  [100 115 118]
  [103 116 118]
  ...
  [230 230 212]
  [233 232 212]
  [234 233 213]]

 [[ 99 114 117]
  [100 115 118]
  [103 116 118]
  ...
  [232 230 212]
  [233 232 212]
  [233 232 212]]

 [[100 115 118]
  [100 115 118]
  [103 116 118]
  ...
  [234 230 211]
  [235 231 212]
  [235 231 212]]

 ...

 [[ 60  48  44]
  [ 52  38  40]
  [ 54  38  49]
  ...
  [167 160 143]
  [167 160 143]
  [167 160 143]]

 [[ 62  47  45]
  [ 58  44  46]
  [ 64  47  60]
  ...
  [166 160 141]
  [166 160 141]
  [166 160 141]]

 [[ 55  40  38]
  [ 38  24  26]
  [ 35  18  32]
  ...
  [166 160 141]
  [166 160 141]
  [166 160 141]]]
[[[115 114 116]
  [115 114 116]
  [116 115 119]
  ...
  [238 230 213]
  [238 230 213]
  [238 230 213]]

 [[112 111 113]
  [115 114 116]
  [117 116 120]
  ...
  [238 230 213]
  [238 230 213]
  [238 230 213]]

 [[110 109 111]
  [115 114 116]
  [118 117 119]
  ...
  [238 230 213]
  [239 232 213]
  [239 232 213]]

 ...

 [[ 60  57  49]
  [ 46  41  32]
  [ 52  43  33]
  ..

[[[112 115 113]
  [111 114 112]
  [112 115 113]
  ...
  [237 231 212]
  [234 230 211]
  [234 230 211]]

 [[114 117 115]
  [113 116 114]
  [112 115 113]
  ...
  [237 231 212]
  [235 231 212]
  [235 231 212]]

 [[116 116 116]
  [114 114 114]
  [113 113 113]
  ...
  [238 232 213]
  [238 233 212]
  [239 234 213]]

 ...

 [[ 52  52  46]
  [ 36  33  28]
  [ 21  14  11]
  ...
  [167 162 141]
  [168 164 140]
  [167 165 141]]

 [[ 50  47  43]
  [ 35  32  28]
  [ 34  26  26]
  ...
  [164 161 140]
  [164 162 138]
  [163 163 139]]

 [[ 42  39  35]
  [ 27  24  20]
  [ 42  34  34]
  ...
  [164 161 140]
  [162 162 138]
  [162 162 138]]]
[[[112 115 113]
  [110 113 111]
  [111 113 113]
  ...
  [235 231 213]
  [238 231 214]
  [238 231 214]]

 [[113 116 114]
  [112 115 113]
  [111 113 113]
  ...
  [237 230 213]
  [238 231 214]
  [238 231 214]]

 [[114 115 113]
  [116 117 115]
  [114 116 116]
  ...
  [238 231 212]
  [238 230 213]
  [238 230 213]]

 ...

 [[ 63  56  53]
  [ 32  27  24]
  [ 30  26  25]
  ..