In [1]:
import numpy as np
import cv2
import socketio
import base64

In [2]:
imdata = 0

sio = socketio.Client()

In [3]:
"""
@는 데코레이터임
https://bluese05.tistory.com/30 설명
"""

@sio.event
def streaming(data):
    data = cv2.imdecode(np.frombuffer(base64.b64decode(data), dtype='uint8'), cv2.IMREAD_COLOR)
    print(data)
    global imdata
    imdata = data

In [5]:
sio.connect('http://localhost:746')

while True:
    sio.on('streaming', streaming)
    cv2.imshow('Person Detect', imdata)
    if cv2.waitKey(1) == 13:
        break
cv2.destroyAllWindows()
sio.disconnect()

[[[107 108 104]
  [107 108 104]
  [108 109 105]
  ...
  [193 184 170]
  [191 183 166]
  [189 181 164]]

 [[109 110 106]
  [108 109 105]
  [108 109 105]
  ...
  [191 183 166]
  [191 183 166]
  [191 184 165]]

 [[108 111 109]
  [106 109 107]
  [106 109 107]
  ...
  [188 182 163]
  [190 184 165]
  [192 187 166]]

 ...

 [[101 128 125]
  [ 98 122 120]
  [ 90 112 110]
  ...
  [167 160 140]
  [170 161 141]
  [170 161 141]]

 [[ 88 126 131]
  [ 93 129 135]
  [ 96 126 131]
  ...
  [172 161 141]
  [173 159 140]
  [173 159 140]]

 [[ 82 124 136]
  [ 85 126 135]
  [ 85 121 129]
  ...
  [175 161 142]
  [174 159 140]
  [173 158 139]]]
[[[109 108 110]
  [108 107 109]
  [111 109 109]
  ...
  [189 182 165]
  [190 182 165]
  [190 182 165]]

 [[106 105 107]
  [106 105 107]
  [107 107 107]
  ...
  [189 182 165]
  [191 183 166]
  [192 184 167]]

 [[105 107 108]
  [103 105 106]
  [104 106 106]
  ...
  [189 182 165]
  [191 183 166]
  [192 184 167]]

 ...

 [[ 94 116 128]
  [100 122 133]
  [ 99 122 130]
  ..

[[[102 109 106]
  [101 108 105]
  [105 109 104]
  ...
  [181 182 162]
  [184 183 162]
  [185 184 163]]

 [[101 108 105]
  [ 99 106 103]
  [100 106 101]
  ...
  [181 182 162]
  [184 183 163]
  [184 183 162]]

 [[ 99 108 105]
  [ 99 106 103]
  [ 99 104 102]
  ...
  [181 181 163]
  [183 181 163]
  [184 183 163]]

 ...

 [[106 124 125]
  [ 95 113 114]
  [ 92 107 109]
  ...
  [165 161 143]
  [164 159 144]
  [164 159 144]]

 [[106 136 141]
  [ 94 123 128]
  [ 97 122 126]
  ...
  [162 159 144]
  [161 158 143]
  [161 158 143]]

 [[ 89 125 131]
  [ 93 127 133]
  [ 84 114 119]
  ...
  [160 157 142]
  [159 156 141]
  [159 156 141]]]
[[[107 110 115]
  [106 109 114]
  [105 108 113]
  ...
  [183 180 165]
  [184 181 166]
  [185 182 167]]

 [[104 107 112]
  [103 106 111]
  [102 105 110]
  ...
  [183 180 165]
  [186 181 166]
  [184 181 166]]

 [[105 105 111]
  [104 104 110]
  [103 104 108]
  ...
  [184 179 164]
  [186 179 164]
  [184 179 164]]

 ...

 [[ 96 124 125]
  [ 93 119 119]
  [ 74  95  96]
  ..